inveniosoftware/invenio-i18n

- AUTHORS.rst
- INSTALL.rst
- docs/api.rst
- invenio_i18n/__init__.py
- invenio_i18n/babel.py
- invenio_i18n/ext.py
- invenio_i18n/jinja2.py
- invenio_i18n/selectors.py
- requirements-devel.txt
- run-tests.sh
- setup.py
- tests/test_invenio_i18n.py
* Improves documentation for both usage guide and API.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> docs: usage guide improvements

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_i18n/version.py
* BETTER Improves selection of the locale using several ways.
(closes #8)
> release: v1.0.0a2

- invenio_i18n/__init__.py
- invenio_i18n/selectors.py
- setup.py
- tests/test_invenio_i18n_selectors.py
* Fixes issue with broken doctest case which seems to have been
caused by third party library. (closes #10)
* Fixes dependency problem with Flask-Login.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> tests: broken tests fix

- invenio_i18n/version.py
> version: post-release bump

- docs/api.rst
- invenio_i18n/__init__.py
- invenio_i18n/ext.py
- invenio_i18n/selectors.py
- invenio_i18n/views.py
- setup.py
- tests/test_invenio_i18n_selectors.py
- tests/test_views.py
* Adds view to set language in session for user.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> views: set language + flask-security fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_i18n/version.py
> release: v1.0.0a3

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_i18n/version.py
> release: v1.0.0a4

- docs/conf.py
- setup.py
- tests/test_invenio_i18n.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: sphinx 1.4.2

- docs/conf.py
- examples/app.py
- invenio_i18n/__init__.py
- invenio_i18n/_compat.py
- invenio_i18n/babel.py
- invenio_i18n/config.py
- invenio_i18n/ext.py
- invenio_i18n/jinja2.py
- invenio_i18n/selectors.py
> global: separation of default config module

- .tx/config
- MANIFEST.in
- README.rst
- docs/index.rst
- invenio_i18n/babel.py
- invenio_i18n/bundles.py
- invenio_i18n/static/js/invenio_i18n/angularLangSelector.js
- invenio_i18n/templates/invenio_i18n/macros/language_selector.html
- invenio_i18n/views.py
- setup.py
- tests/test_invenio_i18n.py
* Add angular factory to set gettext language
* Add bundles.py to compile the factory
(addresses https://github.com/inveniosoftware/invenio-i18n/issues/34)
Signed-off-by: Andrew McCracken <andrew@tind.io>
> factories: add setLanguage factory

- invenio_i18n/ext.py
- invenio_i18n/views.py
* Refactors creation of blueprint to always register static folder
needed for building assets.  (closes #43)
> views: always registered static folder

- .editorconfig
- .gitignore
- CONTRIBUTING.rst
- MANIFEST.in
- docs/Makefile
- docs/conf.py
- docs/examplesapp.rst
- docs/make.bat
- setup.cfg
- setup.py
- tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
> global: release checklist

- invenio_i18n/bundles.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> bundles: addition of missing dependency

- invenio_i18n/__init__.py
> docs: desciption of Transifex integration

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_i18n/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> release: v1.0.0b3

- examples/app.py
- invenio_i18n/static/js/invenio_i18n/angularLangSelector.js
- invenio_i18n/templates/invenio_i18n/macros/language_selector.html
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> template: remove inline JavaScript

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_i18n/version.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> release: v1.0.0b4

- MANIFEST.in
- invenio_i18n/bundles.py
- invenio_i18n/static/js/invenio_i18n/angularLangSelector.js
- invenio_i18n/templates/invenio_i18n/macros/language_selector.html
- invenio_i18n/views.py
- setup.py
- tests/test_invenio_i18n.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> global: add TIND copyright information

- .gitignore
- tests/test_invenio_i18n.py
> tests: fix failing test case due to pytz

- setup.py
- tests/test_invenio_i18n.py
> setup: pytest version pin & test fix

- CHANGES.rst
- invenio_i18n/translations/da/LC_MESSAGES/messages.po
- invenio_i18n/translations/de/LC_MESSAGES/messages.po
- invenio_i18n/translations/es/LC_MESSAGES/messages.po
- invenio_i18n/translations/fr/LC_MESSAGES/messages.po
- invenio_i18n/translations/it/LC_MESSAGES/messages.po
- invenio_i18n/translations/messages.pot
- invenio_i18n/translations/sk/LC_MESSAGES/messages.po
- invenio_i18n/version.py
- tests/test_babel.py
Depends on https://github.com/inveniosoftware/invenio-i18n/pull/93
Closes #90
> release v1.3.0

- .github/workflows/pypi-release.yml
- setup.cfg
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> installation: minor post release fixes

- tests/conftest.py
- tests/test_invenio_i18n.py
- tests/test_invenio_i18n_selectors.py
- tests/test_views.py
- refactor: solve caching problem in teardown
- tests: update expected output due to Babel upgrade
> refactor tests

- invenio_i18n/__init__.py
- invenio_i18n/ext.py
- invenio_i18n/proxies.py
- invenio_i18n/selectors.py
- tests/test_invenio_i18n.py
closes https://github.com/inveniosoftware/invenio-notifications/issues/14
Update `get_locale` selector to also look for `forced_locale` field. A forced locale may be set by the application, to use a specific locale for rendering text.
This PR also includes a small update on the docs `intersphinx_mapping`, due to a deprecation.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to …
> Get forced locale

- CHANGES.rst
- invenio_i18n/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v2.1.0

- CHANGES.rst
- invenio_i18n/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v2.1.1

- invenio_i18n/ext.py
- tests/test_invenio_i18n.py
> ext: allow BABEL_DEFAULT_LOCALE overridability

- .github/workflows/i18n-pull-base.yml
- .github/workflows/i18n-push-base.yml
> Please describe briefly your pull request.
Update reusable workflows to use latest actions (due to warnings)
Update Node version to 18
Update Python version to 3.12
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your …
> github: update reusable workflows

- CHANGES.rst
- invenio_i18n/__init__.py
- setup.cfg
- setup: upper pin packages
- release: v2.2.0
> pin dependencies

- CHANGES.rst
- invenio_i18n/__init__.py
- setup.cfg
- setup: update dependencies
- release: v3.0.0
> bump major

- .github/workflows/i18n-pull-base.yml
- .github/workflows/i18n-push-base.yml
* runs-on: endoflife
* nodejs: endoflife
* python: endoflife
> workflows: update versions of tools

- invenio_i18n/cli.py
- invenio_i18n/config.py
- setup.cfg
- setup.py
This PR introduces commands to:
* Download translations for JS/React modules from Transifex and merge them into a single file.
* Parse merged translation files and distribute translations to the relevant python packages before webpack build. 
This simplifies translation management for frontend modules. See the RFC proposal for details: [inveniosoftware/rfcs#92](https://github.com/inveniosoftware/rfcs/issues/92).
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend** …
> JS Translation Distribution

- .github/workflows/pypi-release.yml
* prevents the compilation step from beeing executed
> fix(actions): babel compile step missing
